background=0xff2e3440
base=0xff2e3440
alternate_base=0xff434c5e
text=0xffd8dee9
bright_text=0xffeceff4
accent=0xff4c566a
accent_secondary=0xff434c5e

font_family=JetBrains Nerd Font

rounding_large=8
rounding_small=4